Traceback (most recent call last):
  File "C:\Users\2025\Desktop\code\_python\webpanel\uploads\test_script.py", line 51, in <module>
    main()
  File "C:\Users\2025\Desktop\code\_python\webpanel\uploads\test_script.py", line 11, in main
    print("\U0001f40d Python Script Started!")
  File "C:\Users\2025\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f40d' in position 0: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2025\Desktop\code\_python\webpanel\uploads\test_script.py", line 56, in <module>
    print(f"\u274c Ошибка: {e}")
  File "C:\Users\2025\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 0: character maps to <undefined>
